import type { Metadata } from "next";
import Header from "@/layouts/header";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
/**global css */
import "./globals.css";
import Footer from "@/layouts/footer";

export const metadata: Metadata = {
  title: "کـــادو باکس",
  description: "Generated by Mohamads",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className="bg-bodyColor"
        data-new-gr-c-s-check-loaded="14.1243.0"
        data-gr-ext-installed=""
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
