import type { Metadata } from "next";
import Header from "@/layouts/header";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
/**global css */
import "./globals.css";
import Footer from "@/layouts/footer";
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: "کـــادو باکس",
  description: "Generated by Mohamads",
};

  
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`bg-bodyColor`}
        suppressHydrationWarning
      >
        <Header />
        {children}
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
